from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture
document.add_picture(
    "profile_picture.jpg",
    width=Inches(2.0)
)

# name, phone number and email details
speak("What is your name? ")
name = input("What is your name? ")

speak("What is your phone number? ")
phone_number = input("What is your phone number? ")

speak("What is your email? ")
email = input("What is your email? ")

document.add_paragraph(
    name + " | " + phone_number + " | " + email
)

# about me
document.add_heading("About me")

speak("Tell me about yourself")
document.add_paragraph(input("Tell about yourself: "))

# work experience
document.add_heading("Work experience")
p = document.add_paragraph()

speak("Do you have work epxerience?")
has_expierences = input("Do you have work experience? Yes or no? ")
if has_expierences.lower() == "yes":
    p = document.add_paragraph()

    speak("Eneter company name")
    company = input("Enter company name: ")
    speak("From date?")
    from_date = input("From Date: ")
    speak("To date?")
    to_date = input("To Date: ")

    p.add_run(company + " ").bold = True
    p.add_run(from_date + "-" + to_date + "\n").italic = True

    speak("Describe your experience at " + company)
    experience_details = input("Describe your experience at " + company + ": ")
    p.add_run(experience_details)

# more experiences
while True:
    speak("Do you have more experiences? Yes or no?")
    has_more_experiences = input("Do you have more experiences? Yes or No? ")
    if has_more_experiences.lower() == "yes":
        p = document.add_paragraph()

        speak("Eneter company name")
        company = input("Enter company name: ")
        speak("From date?")
        from_date = input("From Date: ")
        speak("To date?")
        to_date = input("To Date: ")

        p.add_run(company + " ").bold = True
        p.add_run(from_date + "-" + to_date + "\n").italic = True

        speak("Describe your experience at " + company)
        experience_details = input("Describe your experience at " + company + ": ")
        p.add_run(experience_details)
    else:
        break

# skills
document.add_heading("Skills")
s = document.add_paragraph(style = 'List Bullet')

speak("What is your skill?")
skills = input("Whats your skill? ")
s.add_run(skills)

# more skills
while True:
    speak("Do you have more skills? Yes or No?")
    has_more_skills = input("Do you have more skills? Yes or No? ")
    if has_more_skills.lower() == "yes":
        s = document.add_paragraph(style = 'List Bullet')
        speak("What is your skill?")
        skills = input("What is your skill? ")
        s.add_run(skills)
    else:
        break
    
print("Saving your document.")

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "CV generated by app from @ohornak"

document.save("cv.docx")